### ISSUE TITLE
Create branch `branch/22.08` ?

### ISSUE THREAD

**Issue by Lctrs** [flathub/org.freedesktop.Sdk.Extension.mingw-w64#14]
Now that the beta branch of `com.valvesoftware.Steam` uses the upcoming `22.08` version of the runtime, it would be nice to provide a corresponding branch of this flatpak so that we can build the different proton flatpaks against it to be able to test them with the beta version of the steam flatpak.

**Comment by gasinvein** [comment]
Committed 5576e9f79ff7f7a26e2e69323fd8d4a0d67b0880 on `beta` branch. Although it probably won't just build and will require changes on top of that.

**Comment by Lctrs** [comment]
Looks like it built.

**Comment by gasinvein** [comment]
That was unexpected. Oh well, feel free to test it and tell if it works properly.
